#!/bin/bash

echo "=== Guía de Debug para Odoo ==="
echo ""
echo "🎯 **CONFIGURACIÓN COMPLETADA** 🎯"
echo ""
echo "📋 **Modos disponibles:**"
echo "  1. ./dev.sh start      → Modo normal (sin debug)"
echo "  2. ./dev.sh debug      → Modo debug (no espera cliente)"
echo "  3. ./dev.sh debug-wait → Modo debug (espera cliente)"
echo ""
echo "🐛 **Para usar el debugger:**"
echo ""
echo "1. Inicia en modo debug:"
echo "   ./dev.sh debug"
echo ""
echo "2. En VS Code, ve a Run & Debug (Ctrl+Shift+D)"
echo ""
echo "3. Selecciona 'Python: Remote Attach to Odoo'"
echo ""
echo "4. Presiona F5 para conectar"
echo ""
echo "5. Coloca breakpoints en tus módulos:"
echo "   - Módulos locales: /extra-addons/"
echo "   - Módulos del repo: /mnt/repo-addons/"
echo ""
echo "📁 **Estructura de archivos:**"
echo "   • logs/odoo.log           → Logs detallados"
echo "   • .vscode/launch.json     → Configuración debugger"
echo "   • docker-compose.yml      → Configuración normal"
echo "   • docker-compose.debug.yml → Override para debug"
echo ""
echo "🔗 **URLs importantes:**"
echo "   • Odoo:       http://localhost:8069"
echo "   • PostgreSQL: localhost:5432 (user: odoo, pass: odoo, db: odoo_18)"
echo "   • Valkey:     localhost:6379"
echo "   • Debugger:   localhost:5678"
echo ""
echo "📊 **Comandos útiles:**"
echo "   ./dev.sh status    → Ver estado"
echo "   ./dev.sh logs      → Ver logs en tiempo real"
echo "   ./dev.sh shell     → Abrir shell en contenedor"
echo "   ./dev.sh psql      → Conectar a PostgreSQL"
echo ""
echo "✅ **¡Tu entorno está listo para desarrollo!**"